name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ===========================================================================
  # Deploy to Staging
  # ===========================================================================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'staging'
    environment:
      name: staging
      url: https://staging.guthwine.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_STAGING }}

      - name: Deploy to Kubernetes
        run: |
          # Update image tag
          sed -i "s|ghcr.io/oxford22/guthwine:latest|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" deploy/kubernetes/deployment.yaml
          
          # Apply manifests
          kubectl apply -f deploy/kubernetes/deployment.yaml -n guthwine-staging
          
          # Wait for rollout
          kubectl rollout status deployment/guthwine-api -n guthwine-staging --timeout=300s

      - name: Run smoke tests
        run: |
          # Wait for service to be ready
          sleep 30
          
          # Health check
          curl -f https://staging.guthwine.io/health || exit 1
          
          echo "Staging deployment successful!"

      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # ===========================================================================
  # Deploy to Production
  # ===========================================================================
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.event.inputs.environment == 'production'
    environment:
      name: production
      url: https://api.guthwine.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_PRODUCTION }}

      - name: Run database migrations
        run: |
          kubectl run migrations-${{ github.sha }} \
            --image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-migrations:${{ github.sha }} \
            --restart=Never \
            --rm \
            --wait \
            -n guthwine-production

      - name: Deploy to Kubernetes (Canary)
        run: |
          # Update image tag
          sed -i "s|ghcr.io/oxford22/guthwine:latest|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" deploy/kubernetes/deployment.yaml
          
          # Deploy canary (10% traffic)
          kubectl apply -f deploy/kubernetes/deployment.yaml -n guthwine-production
          kubectl scale deployment guthwine-api --replicas=1 -n guthwine-production
          
          # Wait for canary pod
          kubectl rollout status deployment/guthwine-api -n guthwine-production --timeout=300s

      - name: Canary health check
        run: |
          sleep 60
          
          # Check error rate
          ERROR_RATE=$(curl -s "https://prometheus.guthwine.io/api/v1/query?query=rate(guthwine_errors_total[5m])" | jq '.data.result[0].value[1] // "0"' -r)
          
          if (( $(echo "$ERROR_RATE > 0.01" | bc -l) )); then
            echo "Error rate too high: $ERROR_RATE"
            kubectl rollout undo deployment/guthwine-api -n guthwine-production
            exit 1
          fi
          
          echo "Canary healthy, proceeding with full rollout"

      - name: Full rollout
        run: |
          kubectl scale deployment guthwine-api --replicas=3 -n guthwine-production
          kubectl rollout status deployment/guthwine-api -n guthwine-production --timeout=300s

      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: guthwine
          SENTRY_PROJECT: api
        with:
          environment: production
          version: ${{ github.sha }}
